"""Add status and is_cancelled columns to appointments

Revision ID: 9524e4505e91
Revises: e1a5fe2591f9
Create Date: 2025-12-20 19:39:32.731917

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9524e4505e91'
down_revision: Union[str, Sequence[str], None] = 'e1a5fe2591f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('status', sa.String(length=20), nullable=True))
    op.add_column('appointments', sa.Column('google_event_id', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_appointments_google_event_id'), 'appointments', ['google_event_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_appointments_google_event_id'), table_name='appointments')
    op.drop_column('appointments', 'google_event_id')
    op.drop_column('appointments', 'status')
    # ### end Alembic commands ###
